version: '3.8'

services:
  api:
    image: operacion-fuego-quasar:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Mapea el puerto 80 del contenedor al puerto 5000 del host
    depends_on:
      - db  # Dependencia de la base de datos

  db:
    image: "mcr.microsoft.com/dotnet/aspnet:7.0"
    ports:
      - "1433:1433"  # Puerto predeterminado de SQL Server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"  # Contraseña para el usuario 'sa'
      ACCEPT_EULA: "Y"  # Acepta el acuerdo de licencia de SQL Server
